config/routes.rb
Rails.application.routes.draw do
  get 'picture_books/index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  root "tops#index"
  get 'login' => 'user_sessions#new', :as => :login
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy', :as => :logout
  resources :users, only: %i[create new destroy edit update show]
  resources :calendars
  resources :picture_books
  resources :posts 
end

app/models/calendar.rb
class Calendar < ApplicationRecord
  belongs_to :user
  validates :date_type, presence: true
  validates :record_date, presence: true
  enum date_type: {watering_date: 0, pesticide_date: 1, fertilizer_date: 2}

  def start_time
    self.record_date
  end

  def end_time
    self.record_date
  end
end

app/models/picture_book.rb
class PictureBook < ApplicationRecord
  belongs_to :user 
  mount_uploader :picture, PictureUploader
  attribute :purchase_date, :date, default: Date.current.strftime
  validates :breed, presence: true
  validates :price, length: {maximum: 15}
  validates :shop, length: {maximum: 20}
  validates :purchase_date, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["breed"]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user 
  mount_uploader :image, ImageUploader
  validates :content,  length: {maximum: 80}
def prefecture_name
  JpPrefecture::Prefecture.find(prefecture_code).name
end
end

app/models/user.rb
class User < ApplicationRecord
  include JpPrefecture
  authenticates_with_sorcery!
  mount_uploader :icon, IconUploader
  has_many :posts, dependent: :destroy
  has_many :calendars ,dependent: :destroy
  has_many :picture_books, dependent: :destroy
  validates :email, uniqueness: true, presence: true
  validates :name, presence: true
  validates :password, length: { minimum: 6}, if: -> {new_record? || changes[:crypted_password]}
  validates :password, confirmation: true, if: -> {new_record? || changes[:crypted_password]}
  validates :password_confirmation, presence: true, if: -> {new_record? || changes[:crypted_password]}
  validates :gender, presence: true
  enum gender: {closed: 0, male: 1, female: 2, other: 3}
  jp_prefecture :prefecture_code, presence: true, default:0, method_name: :pref

  def own?(object)
    self.id == object.user_id 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger
  before_action :require_login

  private

  def not_autthenticated
    redirect_to login_path, alert: "先にログインしてください"
  end
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_record, only: %i[edit update destroy]
  def index  
    start_date = params.fetch(:start_date, Date.today).to_date
    @calendars = current_user.calendars.where(user_id: current_user.id, record_date: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week)
  end

  def create
    @calendar = current_user.calendars.build(calendar_params)
    if @calendar.save
      redirect_to calendars_path, success: '日付の登録に成功しました!'
    else
      redirect_to calendars_path,  danger: '日付の登録に失敗しました'
    end
  end
  
  def edit; end
  
  def update
    if @calendar.update(calendar_params)
      redirect_to calendars_path, success: '日付を更新しました'
    else
      flash.now[:danger] = '日付の更新に失敗しました'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @calendar.destroy
    redirect_to calendars_path, success: '日付を削除しました'
  end


  def show
    @calendar = User.find(params[:id])  
  end

  private

  def set_record
    @calendar = current_user.calendars.find(params[:id])  
  end

  def calendar_params
    params.require(:calendar).permit(:date_type, :record_date, :start_date)
  end
end

app/controllers/picture_books_controller.rb
class PictureBooksController < ApplicationController
  before_action :set_picture_book_params, only: %i[edit update destroy]
  def index
    @q = current_user.picture_books.ransack(params[:q])
    @picture_books = @q.result(distinct: true)
  end

  def new
    @picture_book = PictureBook.new
  end

  def create
    @picture_book = current_user.picture_books.build(picture_book_params)
    if @picture_book.save
      redirect_to picture_books_path, success: '図鑑へ登録しました!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def show
    @picture_book = PictureBook.find(params[:id])
  end

  def update
    if @picture_book.update(picture_book_params)
      redirect_to picture_books_path, success: '図鑑を更新しました!'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @picture_book.destroy!
    redirect_to picture_books_path, success: "図鑑のデータを削除しました!"
  end

  private

  def picture_book_params
    params.require(:picture_book).permit(:breed, :price, :shop, :picture, :picture_cache, :purchase_date)
  end

  def set_picture_book_params
    @picture_book = current_user.picture_books.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post ,only: %i[edit update destroy]
  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path, success: '投稿に成功しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post), success: '投稿を編集しました'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post.destroy!
    redirect_to posts_path, status: :see_other, success: '投稿を削除しました'
  end

  private

  def post_params
    params.require(:post).permit(:content, :image, :image_cache)
  end

  def set_post
    @post = current_user.posts.find(params[:id])
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  skip_before_action :require_login
  def index
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to calendars_path, success: 'ログインに成功しました!'
    else
      flash.now[:danger]="ログインできませんでした"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to root_path, success: 'ログアウトに成功しました!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  before_action :set_user, only: %i[show edit  update destroy]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path, success: 'ユーザー作成できました!ログインしてください'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @user.update(user_params)
      redirect_to calendars_path, success: 'ユーザー情報を更新しました!'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def show; end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name, :gender, :prefecture_code, :icon, :icon_cache)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/calendars_helper.rb
module CalendarsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/calendars/_calendar.html.erb
<% if @calendars.nil? %>
  <%= month_calendar do |date| %>
  <%= date %>
<% end %>
<% end %>
<%= turbo_frame_tag 'calendar' do %>
  <%= month_calendar(events: @calendars) do |date, calendars| %>
    <%= date.day %>
    <% calendars.each do |calendar| %>
      <% if calendar.date_type == "watering_date"%>
        <%= link_to image_tag('watering_icon', size: '30x30'), edit_calendar_path(calendar) %>
      <% elsif calendar.date_type =="pesticide_date"%>
        <%= link_to image_tag('pesticide_icon', size:'30x30'), edit_calendar_path(calendar) %>
      <% elsif calendar.date_type == "fertilizer_date" %>
        <%= link_to image_tag('fertilizer_icon', size: '30x30'),edit_calendar_path(calendar) %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/calendars/edit.html.erb
<div class="container">
  <%= form_with model: @calendar, local: true do |f|%>
    <div class="form-group">
      <%= f.label :date_type%></br>
      <%= f.select :date_type, Calendar.date_types_i18n.invert, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :record_date%>
      <%= f.date_field :record_date ,class: 'form-control' %>
    </div>
    <div class="btn-group">
    <%= f.submit '更新' ,class: 'btn btn-danger'%>
  <% end %>
  <%= link_to'カレンダーに戻る', calendars_path, class: 'btn btn-warning'%>
  <%=button_to'削除', calendar_path(@calendar), method: :delete  ,class: 'btn btn-success'%>
  </div>
</div>

app/views/calendars/index.html.erb
<div class="container-fluid">
  <div class="input-record"> 
    <h1>登録する日付を入力してください</h1>
    <%= form_with model: Calendar.new,url: calendars_path,local: true do |f|%>
      <div class="form-group">
        <%= f.label :date_type%></br>
        <%= f.select :date_type, Calendar.date_types_i18n.invert, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :record_date%>
        <%= f.date_field :record_date, class:'form-control' %>
      </div>
      <%= f.submit class: 'btn btn-danger'%>
    <% end %>
  </div>
  <div id="calendar">
    <%= render 'calendar', logs: @logs %>
  </div>
  <div class="icon">
    <%= image_tag 'watering_icon', size: '40x40' %><p>: 水やり</p>
  </div>
  <div class="icon">
    <%= image_tag 'pesticide_icon', size: '40x40' %><p>: 薬剤</p>
  </div>
  <div class="icon">
    <%= image_tag 'fertilizer_icon', size: '40x40' %><p>: 肥料</p>
  </div>
</div>

app/views/calendars/index.js.erb
$('#calendar').html("<%= j(render 'calendar', @calendars: @calendars));

app/views/calendars/show.html.erb
<%= turbo_frame_tag 'calendar' do %>
  <%= month_calendar do |date| %>
    <%= date.day %>
  <% end %>
<% end %>

<div class="icon">
  <%= image_tag 'watering_icon', size: '50x50' %><p>: 水やり</p>
</div>
<div class="icon">
  <%= image_tag 'pesticide_icon', size: '50x50' %><p>: 薬剤</p>
</div>
<div class="icon">
  <%= image_tag 'fertilizer_icon', size: '50x50' %><p>: 肥料</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>私の多肉こよみ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </head>

  <body>
    <% if logged_in? %>
      <%= render 'shared/login_header' %>
      <%= render 'shared/menu_bar' %>
    <% else %>
      <%= render 'shared/header' %>
    <% end %>
    <%= render 'shared/flash_message' %>
    <%= yield %>
  </body>
</html>

app/views/picture_books/_form.html.erb
<%= form_with model: @picture_book, local: true do |f|  %> 
  <%=render 'shared/error_messages' , object: f.object %> 
  <div class="container">  
    <div class="form-group">
      <%= f.label :breed %> 
      <%= f.text_field :breed ,class:'form-control' , placeholder: "例)名無し"%>
    </div>
    <div class="col-2">
      <%= f.label :price %>
    <div class="input-group mb-3 me-5">
      <%= f.text_field :price , class: 'form-control ' ,placeholder: "例)100"%>
      <span class="input-group-text" id="basic-addon1">円</span>
    </div></div>
    <div class="form-group">
      <%= f.label :shop %>
      <%= f.text_field :shop ,class: 'form-control' , placeholder: "例)ホームセンター"%>
    </div>
    <div class="form-group">
      <%= f.label :picture %>
      <%= f.file_field :picture %>
      <%= f.hidden_field :picture_cache ,class: 'form-control'%>
    </div>
    <div class="form-group mb-3">
      <%= f.label :purchase_date%>
      <%= f.date_field :purchase_date, class: 'form-control'%>
    </div>
    <%= f.submit '保存', class: 'btn btn-danger'%>
  </div>
<% end %>

app/views/picture_books/_picture_book.html.erb
<div class="col-auto" >
    <div class="card-body">
      <div class="card">
        <%= link_to (image_tag picture_book.picture_url , size: "200x200"), picture_book_path(picture_book.id), class: "picture-image"%>
        <h5 class="card-title"><%=link_to picture_book.breed , picture_book_path(picture_book.id)%></h5>
      </div>
    </div>
</div>

app/views/picture_books/_search_form.html.erb
<%= search_form_for @q, url: url , class: "search-bar" do |f| %>
  <div class="input-group mb-3",style=background-color:#cfe0a3; >
    <%= f.label :breed, "図鑑の検索", class: "search-title"%>
    <%= f.search_field :breed_cont, class: 'form-control', placeholder: "品種名を入力してください"%>
    <span class="input-group-btn input-group-append">
      <%=f.submit "検索",  class: "btn btn-danger"   %>
    </span>
  </div>
<% end %>

app/views/picture_books/edit.html.erb
<div class="container">
  <h1>図鑑編集</h1>
  <%= render 'form' , model: @picture_book%>
</div>

app/views/picture_books/index.html.erb
 <div class="container">
  <%= render 'search_form', url: picture_books_path %>
  <div class="row current-user">
    <h1><%= current_user.name %>さんの多肉図鑑</h1>
    <%=button_to '追加する', new_picture_book_path, {method: :get, class: "btn btn-danger picture_add_btn"}%>
  </div>
</div>
<div class="container picture-container">
  <div class="row">
    <div class="col-lg">
      <div class="row">
        <% if @picture_books.present? %>
          <%= render @picture_books %>
        <% else %>
          <h1>また図鑑への登録がありません。右上から登録してみましょう!</h1>
        <% end %>
        </div>
    </div>
  </div>
</div>

app/views/picture_books/new.html.erb
<div class="container picture-books-container">
  <div class="row">
    <%=render 'form' , model: @picture_book%>
  </div>
</div>

app/views/picture_books/show.html.erb
<div class="container">
  <div class="card  mt-5" style="width: auto; padding: 0px;">
    <h1 class="card-title"><%= @picture_book.breed%></h1>
    <%=  l @picture_book.created_at, format: :short%>
    <%= image_tag @picture_book.picture_url, size: "200x200"%>
    <ul class="list-group list-group-flush">
      <% if @picture_book.price.blank? %>
        <li class="list-group-item">価格: 未設定</li>
      <% else %>
        <li class="list-group-item">価格: <%= @picture_book.price %></li>
      <% end %>
      <% if @picture_book.shop.blank? %>
        <li class="list-group-item">購入店舗: 未設定</li>
      <% else %>
        <li class="list-group-item">購入店舗: <%= @picture_book.shop %></li>
      <%end%>  
        <li class="list-group-item">購入日: <%= @picture_book.purchase_date%></li>
    </ul>
  </div>
  <% if current_user&.own?(@picture_book)%>
    <div class="btn-group cred-btn ms-5">
      <%= button_to '編集', edit_picture_book_url(@picture_book) ,method: :get, class: "btn btn-success" %>
      <%= button_to '削除', picture_book_url(@picture_book),  method: :delete, class: "btn btn-danger",form: { data: { turbo_confirm: '削除しますか?' }} %>
    </div>
  <% end %>
  </div>
</div>

app/views/posts/_button.html.erb
<div class="fixed-post-button ">
  <%= button_to'投稿', new_post_path, method: :get, class: "btn btn-danger  large-post-button"%>
</div>

app/views/posts/_post.html.erb
<div class="container ">
  <div class="card my-3 ">
    <%=link_to (post_path(post.id)), class:"post-detail-link" do%>
      <div class="row">
        <div class="col">
          <%= image_tag post.image_url, size: '300x200'%>
        </div>
        <div class="col">
            <%= image_tag post.user.icon.url, size: '50x50', class: "post-icon"%>
          <div class="row user-name">
            <%= post.user.name%>
            <%= post.user.pref.name%>
          </div>
          <div class="row-mx-5 content">  
            <%= post.content%>
          </div>
          <div class="row align-bottom">
            <p>投稿日:<%= post.updated_at.strftime("%Y-%m-%d")%></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div

app/views/posts/edit.html.erb
<div class="container m-5" >
  <h1>投稿内容</h1> 
  <div class="row my-4">
    <%= form_with model: @post, local: true do |f| %>
      <%= render 'shared/error_messages' , object: f.object %>
      <div class="form-group">
        <%= f.label :content , class: "post-label"%>
        <%= f.text_area :content , class: 'form-control', placeholder: "投稿する内容を入力してください", size: '30x10'%>
      </div>
      <div class="form-group">
        <%= f.label :image, class: "post-label" %></br>
        <%= f.file_field :image ,accept: 'image/*'%>
        <%= f.hidden_field :image_cache%>
        <%= image_tag @post.image.url, size:'200x200'%>
      </div>
      <%= f.submit '編集' , class: "btn btn-danger my-3 post-button"%>
    <% end %>
</div>

app/views/posts/index.html.erb
<div class="container ">  
  <%= render 'button'%>
  <% if @posts.present? %>
      <%=render @posts%>
  <% else%>
    <div class="index-post">
      <h1>まだ投稿がありません</h1>
    </div>
  <% end%>
</div>

app/views/posts/new.html.erb
<div class="container " >
  <h1>投稿内容</h1> 
  <div class="row my-4">
    <%= form_with model: @post, local: true do |f| %>
      <%= render 'shared/error_messages' , object: f.object %>
      <div class="form-group">
        <%= f.label :content , class: "post-label"%>
        <%= f.text_area :content , class: 'form-control', placeholder: "投稿する内容を入力してください", size: '30x10'%>
      </div>
      <div class="form-group">
        <%= f.label :image, class: "post-label" %></br>
        <%= f.file_field :image %>
      </div>
      <%= f.submit '投稿' , class: "btn btn-danger my-3 post-button"%>
    <% end %>
</div>

app/views/posts/show.html.erb
<div class="container post-show">
  <div class="card">
      <div class="row">
        <div class="col">
          <%= image_tag @post.image_url, size: '500x400',class: "post-img"%>
        </div>
        <div class="col">
            <%= image_tag @post.user.icon.url, size: '100x100', class: "post-icon"%>
          <div class="row user-name">
            <%= @post.user.name%>
            <%= @post.user.pref.name%>
          </div>
          <div class="row-mx-5 detail-content">  
            <%= @post.content%>
          </div>
          <div class="row align-bottom detail-date">
            <p>投稿日:<%= @post.updated_at.strftime("%Y-%m-%d")%></p>
          </div>
          <% if current_user&.own?(@post)%>
            <div class="row">
              <div class="col">
                <%=link_to'編集' , edit_post_path(@post), class:"cred-button"%>
                <%= link_to '削除', post_path(@post),class: "cred-button", form: { data: { turbo_confirm: '削除しますか?' }} ,data: { turbo_method: :delete } %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
  </div>
</div

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <nav class = "navbar navbar-expand navbar-light fixed-top" style="background-color: #88ab36; height: 50px;">
    <div class = "container-fluid">
      <%= link_to '私の多肉こよみ', root_path,  class: "navbar-brand" %>
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class = "nav-item">
          <%= link_to 'ログイン', login_path , class: "nav-link"%>
        </li>
        <li class = "nav-item">  
          <%= link_to '新規登録', new_user_path, class: "btn btn-success btn-block" %>
        </li>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_login_header.html.erb
<header>
  <nav class = "navbar navbar-expand  fixed-top" style="background-color: #88ab36; height: 50px;">
    <div class = "container-fluid">
      <%= link_to '私の多肉こよみ', root_path, class: "navbar-brand" %>
      <ul class="navbar-nav mb-2 ">
        <li class = "nav-item">
          <%= image_tag current_user.icon_url, size: "50x50"%>
        </li>
        <li class="nav-item">
        <div class="dropdown">
            <button type="button" class="btn btn-light dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
              メニュー
            </button>
            <ul class="dropdown-menu">
              <li><%= link_to 'マイページ', calendars_path,class: "dropdown-item" %></li>
              <li><%= link_to '設定' ,edit_user_path(current_user), class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to 'ログアウト' ,logout_path, data: { turbo_method: :delete },class:"dropdown-item" %></li>
          </ul>
        </div>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_menu_bar.html.erb
<header class="menu">
  <nav class="navbar navbar-expand" style="background-color: #ffb62f; height: 50px;">
    <div class="container-fluid">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 menu-nav">
        <li><%= link_to 'マイページ', calendars_path ,class:"nav-item menu-bar me-4"%></li>
        <li><%= link_to '私の多肉図鑑', picture_books_path,class:"nav-item menu-bar me-4"%></li>
        <li><%= link_to 'タイムライン', posts_path,class:"nav-item menu-bar me-4"%></li>
      </ul>
    </div>
  </nav>
</header>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), start_date.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), start_date.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view ,class: "btn btn-danger calendar-btn",remote:true%>
    <span class="calendar-title"><%= start_date.year %>年&emsp;<%= t('date.month_names')[start_date.month] %> </span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view ,class: "btn btn-danger calendar-btn", remote:true%>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), start_date.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), start_date.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tops/index.html.erb
  <div class="logo-area">
    <%= image_tag('logo.png')%>
  </div>
  <div class="top-content">
    <p>多肉がきれいな時も、元気がない時も、買ったばかりの時も</p>
    <p>記録していく</p>
    <p>多肉記録サービスです</p>
    <%= link_to'新規登録して使ってみる', new_user_path, class: 'btn btn-success'%>
  </div>

app/views/user_sessions/new.html.erb
<div class="container">
  <div class="row">
    <%= form_with model: @user, local: true do |f| %>
      <div class="form-group">
        <%= f.label :email, "メールアドレス"%>
        <%= f.email_field :email , class: 'form-control'%>
      </div>
      <div class="form-group">
        <%= f.label :password ,"パスワード"%>
        <%= f.password_field :password , class: 'form-control'%>
      </div></br>
      <div class="form-group">
        <%= f.submit 'ログイン' , class: "btn btn-danger", id: "login-button"%>
      </div>
    <% end %>
  </div>  
</div>